runner:
  use: thread
  max_workers: 3
  timeout: null

database:
  host: mongodb://localhost/mtask

logging:
  version: 1
  formatters:
    acquire:
      format: ACQUIRE - %(message)s
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      stream: ext://sys.stdout
    console-acquire:
      class: logging.StreamHandler
      level: INFO
      stream: ext://sys.stdout
      formatter: acquire
  loggers:
    runner:
      handlers: [console]
      level: INFO
    task.acquire:
      handlers: [console-acquire]
      level: INFO